### PR TITLE
Add gha using goreleaser

### PR DESCRIPTION
**Pull request by Firefishy**
Simplified build using go-releaser. 

* Builds both `ARM64` and `AMD64` releases.

### CODE REVIEW

**Comment by Firefishy** [comment]
The existing build of `exim_exporter` is not compatible with musl (aka alpine). If wanted I could also add musl builds in this PR.

**Comment by Firefishy** [comment]
@gvengel Is this worth pursuing further?

I'd like to see an `ARM64` release exim_exporter. This PR builds a glibc compatible releases for `ARM64` and `AMD64`.

**Comment by Firefishy** [comment]
Example build (ignore the version number and changes): https://github.com/Firefishy/exim_exporter/releases/tag/v0.1.9

**Comment by gvengel** [comment]
Thanks @Firefishy,

Adding arm64 binaries to the release seems good, and I'm happy to working on getting it integrated.

Is there a particular reason you want to switch the build to Github Actions instead of the existing Travis CI implementation? I have no strong reason to prefer Travis CI, other than I haven't used Github Actions, so I'll have to RTFM and make sure I'm up to speed.

**Comment by Firefishy** [comment]
Travis CI seem to has been dying a slow death and has been curtailing their free offering to Open Source projects after the move to travis-ci.org -> travis-ci.com. They have also suffered some serious security leaks.

GitHub actions integrates nicely into GitHub, has a reasonably clean syntax and seems to be well supported.

**Comment by gvengel** [comment]
Fair enough! I've been meaning to play around with Github Actions anyway, so I'll find sometime to give it a go soon, then let you know what I decide.

**Comment by Firefishy** [comment]
FYI `exim_exporter` works well on ARM64. [Here is is running](https://prometheus.openstreetmap.org/d/cCA-wjpGz/mail-service?orgId=1&refresh=1m&var-instance=palulukon) on an AWS Graviton2 VM (ARM64). I've also briefly tested it on a Apple M1 linux docker container. 

Thank you ♥

**Comment by Firefishy** [comment]
Here is a reasonably clean goreleaser example for a larger project (also using GitHub Actions): https://github.com/StackExchange/dnscontrol/blob/master/.goreleaser.yml

**Comment by gvengel** [comment]
Thanks. I did actually spend some time investigating this, and went as far as switching to goreleaser for another project. Unfortunately, the main release of exim_exporter uses CGO for systemd journald support, and it makes things "[trickier](https://goreleaser.com/limitations/cgo/)". Figuring out a solution is still on my todo list, just haven't found the time for it yet.

**Comment by gvengel** [comment]
Yeah, sorry my last comment missed the mark there, @Firefishy. The work you did to support cross compilation is great, thanks! 

The delay here has been self-imposed, as I wanted to do a clean room port to goreleaser and github actions. That way I would fully understand how it was all put together, and could maintain it going forward. I've been working towards that in a private repo so I could test the release process end-to-end. 

I've integrated your work to support cross compilation into my private implementation and pulled everything over to a new branch, [goreleaser](/gvengel/exim_exporter/tree/goreleaser). Any comments would be welcome. 

The goreleaser+gha builds have been running on my production servers for the last couple weeks, and I haven't seen any issues. If you have time to try the arm64 [artifacts](/gvengel/exim_exporter/actions/runs/5301822608), that would great! They past tests, but I don't have real arm64 servers to catch any edge cases. 

I should have time to get this integrated into main this weekend, and start preparing the next official release using the new system. 🎉

**Comment by gvengel** [comment]
All changes have been directly or indirectly merged into main. Thanks again!

**Pull request closed without merging**
